name: flutter_cupertino_date_picker
description: Flutter cupertino date picker. Display DatePicker in iOS style. Support both Android and iOS platform.
version: 1.1.0
author: Dylan Wu <dylanwuzh@gmail.com>
homepage: https://github.com/wuzhendev/flutter-cupertino-date-picker

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
